Repository INDAPlus20/brynolv-evper-ofjall-project, pull requests merged in 2021-04, with the labels that each got.

#7 Adds compilation and debugging instructions
  README.md
Labels: documentation

#8 Adds rust workflow
  .github/workflows/rust.yml
Labels: enhancement

#15 Runs rustfmt and adds comments
  src/main.rs
  src/printer.rs
Labels: documentation

#23 Adds PIC
  src/pic.rs
Labels: enhancement

#21 Adds llvm-tools as a dependency in the readme.
  README.md
Labels: documentation

#29 Adds code comments.
  src/idt.rs
Labels: documentation

#27 Fixes build.py assuming ./out/ exists
  build.py
Labels: bug

#28 Adds PS/2 keyboard support
  Cargo.toml
  src/main.rs
  src/printer.rs
  src/ps2.rs
  src/ps2_keyboard.rs
  src/svec.rs
  src/vgafont.bin
Labels: enhancement

#22 Adds support for PS/2 features
  Cargo.toml
  src/gdt.rs
  src/idt.rs
  src/main.rs
  src/pic.rs
  src/printer.rs
  src/ps2.rs
  src/ps2_keyboard.rs
  src/svec.rs
  src/vgafont.bin
Labels: enhancement, good first issue, help wanted
