Repository INDAPlus20/brynolv-evper-ofjall-project, pull requests merged in 2021-05, with the labels that each got.

#37 Documents module initializer orderings
  src/gdt.rs
  src/idt.rs
  src/main.rs
  src/pic.rs
  src/printer.rs
  src/ps2.rs
  src/ps2_keyboard.rs
Labels: documentation

#41 PATA support
  src/harddisk/pata.rs
Labels: bug, enhancement, wontfix

#44 Added rustfmt config and enforced it with GitHub Action
  .github/workflows/fmt.yml
  .rustfmt.toml
  src/gdt.rs
  src/idt.rs
  src/main.rs
  src/pic.rs
  src/printer.rs
  src/ps2.rs
  src/ps2_keyboard.rs
  src/svec.rs
Labels: enhancement

#36 Adds support for reading and writing to harddisks
  .cargo/config.toml
  Cargo.toml
  bios.bin
  build.py
  file_to_write.txt
  insert-file.sh
  src/allocator.rs
  src/harddisk/fat32.rs
  src/harddisk/mod.rs
  src/harddisk/partitions.rs
  src/harddisk/pata.rs
  src/main.rs
  src/ps2_keyboard.rs
  src/svec.rs
  test.txt
Labels: enhancement
